// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PACKAGE_ASSETPACK_H_
#define FLATBUFFERS_GENERATED_PACKAGE_ASSETPACK_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

#include "Font_generated.h"
#include "Scene_generated.h"
#include "Sprite_generated.h"
#include "common_generated.h"
#include "prefab_generated.h"

namespace AssetPack {

struct Package;
struct PackageBuilder;

struct Package FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PackageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SPRITENAMES = 4,
    VT_SPRITEIDS = 6,
    VT_FONTNAMES = 8,
    VT_FONTIDS = 10,
    VT_PREFABNAMES = 12,
    VT_SCENENAMES = 14,
    VT_RESOURCEFILENAMES = 16,
    VT_RESOURCEFILESIZES = 18,
    VT_SPRITES = 20,
    VT_FONTS = 22,
    VT_PREFABS = 24,
    VT_SCENES = 26
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *spriteNames() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_SPRITENAMES);
  }
  const ::flatbuffers::Vector<uint32_t> *spriteIDs() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_SPRITEIDS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *fontNames() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_FONTNAMES);
  }
  const ::flatbuffers::Vector<uint32_t> *fontIDs() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_FONTIDS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *prefabNames() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_PREFABNAMES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *sceneNames() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_SCENENAMES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *resourceFileNames() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_RESOURCEFILENAMES);
  }
  const ::flatbuffers::Vector<uint32_t> *resourceFileSizes() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_RESOURCEFILESIZES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<AssetPack::Sprite>> *sprites() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<AssetPack::Sprite>> *>(VT_SPRITES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<AssetPack::Font>> *fonts() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<AssetPack::Font>> *>(VT_FONTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<AssetPack::Prefab>> *prefabs() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<AssetPack::Prefab>> *>(VT_PREFABS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<AssetPack::Scene>> *scenes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<AssetPack::Scene>> *>(VT_SCENES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SPRITENAMES) &&
           verifier.VerifyVector(spriteNames()) &&
           verifier.VerifyVectorOfStrings(spriteNames()) &&
           VerifyOffset(verifier, VT_SPRITEIDS) &&
           verifier.VerifyVector(spriteIDs()) &&
           VerifyOffset(verifier, VT_FONTNAMES) &&
           verifier.VerifyVector(fontNames()) &&
           verifier.VerifyVectorOfStrings(fontNames()) &&
           VerifyOffset(verifier, VT_FONTIDS) &&
           verifier.VerifyVector(fontIDs()) &&
           VerifyOffset(verifier, VT_PREFABNAMES) &&
           verifier.VerifyVector(prefabNames()) &&
           verifier.VerifyVectorOfStrings(prefabNames()) &&
           VerifyOffset(verifier, VT_SCENENAMES) &&
           verifier.VerifyVector(sceneNames()) &&
           verifier.VerifyVectorOfStrings(sceneNames()) &&
           VerifyOffset(verifier, VT_RESOURCEFILENAMES) &&
           verifier.VerifyVector(resourceFileNames()) &&
           verifier.VerifyVectorOfStrings(resourceFileNames()) &&
           VerifyOffset(verifier, VT_RESOURCEFILESIZES) &&
           verifier.VerifyVector(resourceFileSizes()) &&
           VerifyOffset(verifier, VT_SPRITES) &&
           verifier.VerifyVector(sprites()) &&
           verifier.VerifyVectorOfTables(sprites()) &&
           VerifyOffset(verifier, VT_FONTS) &&
           verifier.VerifyVector(fonts()) &&
           verifier.VerifyVectorOfTables(fonts()) &&
           VerifyOffset(verifier, VT_PREFABS) &&
           verifier.VerifyVector(prefabs()) &&
           verifier.VerifyVectorOfTables(prefabs()) &&
           VerifyOffset(verifier, VT_SCENES) &&
           verifier.VerifyVector(scenes()) &&
           verifier.VerifyVectorOfTables(scenes()) &&
           verifier.EndTable();
  }
};

struct PackageBuilder {
  typedef Package Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_spriteNames(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> spriteNames) {
    fbb_.AddOffset(Package::VT_SPRITENAMES, spriteNames);
  }
  void add_spriteIDs(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> spriteIDs) {
    fbb_.AddOffset(Package::VT_SPRITEIDS, spriteIDs);
  }
  void add_fontNames(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> fontNames) {
    fbb_.AddOffset(Package::VT_FONTNAMES, fontNames);
  }
  void add_fontIDs(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> fontIDs) {
    fbb_.AddOffset(Package::VT_FONTIDS, fontIDs);
  }
  void add_prefabNames(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> prefabNames) {
    fbb_.AddOffset(Package::VT_PREFABNAMES, prefabNames);
  }
  void add_sceneNames(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> sceneNames) {
    fbb_.AddOffset(Package::VT_SCENENAMES, sceneNames);
  }
  void add_resourceFileNames(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> resourceFileNames) {
    fbb_.AddOffset(Package::VT_RESOURCEFILENAMES, resourceFileNames);
  }
  void add_resourceFileSizes(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> resourceFileSizes) {
    fbb_.AddOffset(Package::VT_RESOURCEFILESIZES, resourceFileSizes);
  }
  void add_sprites(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<AssetPack::Sprite>>> sprites) {
    fbb_.AddOffset(Package::VT_SPRITES, sprites);
  }
  void add_fonts(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<AssetPack::Font>>> fonts) {
    fbb_.AddOffset(Package::VT_FONTS, fonts);
  }
  void add_prefabs(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<AssetPack::Prefab>>> prefabs) {
    fbb_.AddOffset(Package::VT_PREFABS, prefabs);
  }
  void add_scenes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<AssetPack::Scene>>> scenes) {
    fbb_.AddOffset(Package::VT_SCENES, scenes);
  }
  explicit PackageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Package> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Package>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Package> CreatePackage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> spriteNames = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> spriteIDs = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> fontNames = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> fontIDs = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> prefabNames = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> sceneNames = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> resourceFileNames = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> resourceFileSizes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<AssetPack::Sprite>>> sprites = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<AssetPack::Font>>> fonts = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<AssetPack::Prefab>>> prefabs = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<AssetPack::Scene>>> scenes = 0) {
  PackageBuilder builder_(_fbb);
  builder_.add_scenes(scenes);
  builder_.add_prefabs(prefabs);
  builder_.add_fonts(fonts);
  builder_.add_sprites(sprites);
  builder_.add_resourceFileSizes(resourceFileSizes);
  builder_.add_resourceFileNames(resourceFileNames);
  builder_.add_sceneNames(sceneNames);
  builder_.add_prefabNames(prefabNames);
  builder_.add_fontIDs(fontIDs);
  builder_.add_fontNames(fontNames);
  builder_.add_spriteIDs(spriteIDs);
  builder_.add_spriteNames(spriteNames);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Package> CreatePackageDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *spriteNames = nullptr,
    const std::vector<uint32_t> *spriteIDs = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *fontNames = nullptr,
    const std::vector<uint32_t> *fontIDs = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *prefabNames = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *sceneNames = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *resourceFileNames = nullptr,
    const std::vector<uint32_t> *resourceFileSizes = nullptr,
    const std::vector<::flatbuffers::Offset<AssetPack::Sprite>> *sprites = nullptr,
    const std::vector<::flatbuffers::Offset<AssetPack::Font>> *fonts = nullptr,
    const std::vector<::flatbuffers::Offset<AssetPack::Prefab>> *prefabs = nullptr,
    const std::vector<::flatbuffers::Offset<AssetPack::Scene>> *scenes = nullptr) {
  auto spriteNames__ = spriteNames ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*spriteNames) : 0;
  auto spriteIDs__ = spriteIDs ? _fbb.CreateVector<uint32_t>(*spriteIDs) : 0;
  auto fontNames__ = fontNames ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*fontNames) : 0;
  auto fontIDs__ = fontIDs ? _fbb.CreateVector<uint32_t>(*fontIDs) : 0;
  auto prefabNames__ = prefabNames ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*prefabNames) : 0;
  auto sceneNames__ = sceneNames ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*sceneNames) : 0;
  auto resourceFileNames__ = resourceFileNames ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*resourceFileNames) : 0;
  auto resourceFileSizes__ = resourceFileSizes ? _fbb.CreateVector<uint32_t>(*resourceFileSizes) : 0;
  auto sprites__ = sprites ? _fbb.CreateVector<::flatbuffers::Offset<AssetPack::Sprite>>(*sprites) : 0;
  auto fonts__ = fonts ? _fbb.CreateVector<::flatbuffers::Offset<AssetPack::Font>>(*fonts) : 0;
  auto prefabs__ = prefabs ? _fbb.CreateVector<::flatbuffers::Offset<AssetPack::Prefab>>(*prefabs) : 0;
  auto scenes__ = scenes ? _fbb.CreateVector<::flatbuffers::Offset<AssetPack::Scene>>(*scenes) : 0;
  return AssetPack::CreatePackage(
      _fbb,
      spriteNames__,
      spriteIDs__,
      fontNames__,
      fontIDs__,
      prefabNames__,
      sceneNames__,
      resourceFileNames__,
      resourceFileSizes__,
      sprites__,
      fonts__,
      prefabs__,
      scenes__);
}

inline const AssetPack::Package *GetPackage(const void *buf) {
  return ::flatbuffers::GetRoot<AssetPack::Package>(buf);
}

inline const AssetPack::Package *GetSizePrefixedPackage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<AssetPack::Package>(buf);
}

inline bool VerifyPackageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<AssetPack::Package>(nullptr);
}

inline bool VerifySizePrefixedPackageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<AssetPack::Package>(nullptr);
}

inline void FinishPackageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<AssetPack::Package> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPackageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<AssetPack::Package> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace AssetPack

#endif  // FLATBUFFERS_GENERATED_PACKAGE_ASSETPACK_H_
