// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PREFAB_ASSETPACK_H_
#define FLATBUFFERS_GENERATED_PREFAB_ASSETPACK_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");

#include "SceneData_generated.h"
#include "common_generated.h"

namespace AssetPack {

struct Prefab;
struct PrefabBuilder;

struct Prefab FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PrefabBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_SCENEDATA = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const AssetPack::SceneData *sceneData() const {
    return GetPointer<const AssetPack::SceneData *>(VT_SCENEDATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_SCENEDATA) &&
           verifier.VerifyTable(sceneData()) &&
           verifier.EndTable();
  }
};

struct PrefabBuilder {
  typedef Prefab Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Prefab::VT_NAME, name);
  }
  void add_sceneData(::flatbuffers::Offset<AssetPack::SceneData> sceneData) {
    fbb_.AddOffset(Prefab::VT_SCENEDATA, sceneData);
  }
  explicit PrefabBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Prefab> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Prefab>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Prefab> CreatePrefab(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<AssetPack::SceneData> sceneData = 0) {
  PrefabBuilder builder_(_fbb);
  builder_.add_sceneData(sceneData);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Prefab> CreatePrefabDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    ::flatbuffers::Offset<AssetPack::SceneData> sceneData = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return AssetPack::CreatePrefab(
      _fbb,
      name__,
      sceneData);
}

inline const AssetPack::Prefab *GetPrefab(const void *buf) {
  return ::flatbuffers::GetRoot<AssetPack::Prefab>(buf);
}

inline const AssetPack::Prefab *GetSizePrefixedPrefab(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<AssetPack::Prefab>(buf);
}

inline bool VerifyPrefabBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<AssetPack::Prefab>(nullptr);
}

inline bool VerifySizePrefixedPrefabBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<AssetPack::Prefab>(nullptr);
}

inline void FinishPrefabBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<AssetPack::Prefab> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPrefabBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<AssetPack::Prefab> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace AssetPack

#endif  // FLATBUFFERS_GENERATED_PREFAB_ASSETPACK_H_
