
#pragma once

#include <stdint.h>

#include "VKEngine.h"
#include "ShaderTypes.h"
#include "pipeline.h"

/*
    Generated by ShaderReflector tool
*/

namespace ShaderUtil
{

	template<typename T>
	void CreateMappedInstanceBuffer(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<T>& buffer);

	template<typename T>
	void CreateMappedInstanceBuffer(VKEngine* engine, MappedDoubleBuffer<T>& buffer);

	void coloredQuad_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::ColoredQuadInstaceBuffer> _ColoredQuadInstaceBuffer,
		LinkedBindableBuffer<ShaderTypes::CamerUBO> _CamerUBO
	);
	void coloredTriangles_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::ColoredTriangleInstaceBuffer> _ColoredTriangleInstaceBuffer,
		LinkedBindableBuffer<ShaderTypes::CamerUBO> _CamerUBO
	);
	void particleSystem_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::ParticalSmallGroupInstanceBuffer> _ParticalSmallGroupInstanceBuffer,
		LinkedBindableBuffer<ShaderTypes::ParticalLargeGroupInstanceBuffer> _ParticalLargeGroupInstanceBuffer,
		LinkedBindableBuffer<ShaderTypes::CamerUBO> _CamerUBO
	);
	void text_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::TextHeaderInstaceBuffer> _TextHeaderInstaceBuffer,
		LinkedBindableBuffer<ShaderTypes::TextDataInstaceBuffer> _TextDataInstaceBuffer,
		LinkedBindableBuffer<ShaderTypes::CamerUBO> _CamerUBO,
		LinkedBindableBuffer<ShaderTypes::TextIndexInstaceBuffer> _TextIndexInstaceBuffer
	);
	void texture_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::TexturedQuadInstaceBuffer> _TexturedQuadInstaceBuffer,
		LinkedBindableBuffer<ShaderTypes::LightMapUBO> _LightMapUBO,
		LinkedBindableBuffer<ShaderTypes::CamerUBO> _CamerUBO
	);
	void tilemap_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::mapFGObjectBuffer> _mapFGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapBGObjectBuffer> _mapBGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::CamerUBO> _CamerUBO
	);
	void tilemapLightRaster_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::mapFGObjectBuffer> _mapFGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapBGObjectBuffer> _mapBGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapUpscaleObjectBuffer> _mapUpscaleObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapBlurObjectBuffer> _mapBlurObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::CamerUBO> _CamerUBO
	);



} // namespace
        