
#pragma once

#include <stdint.h>

#include "VKEngine.h"
#include "pipeline.h"
#include "ShaderTypes.h"

/*
    Generated by ShaderReflector tool
*/

namespace ShaderUtil
{

	template<typename T>
	void CreateMappedInstanceBuffer(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<T>& buffer);

	template<typename T>
	void CreateMappedInstanceBuffer(VKEngine* engine, MappedDoubleBuffer<T>& buffer);

	PipelineResourceConfig coloredQuad_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::ColoredQuadInstaceBuffer>  _ColoredQuadInstaceBuffer,
		LinkedBindableBuffer<ShaderTypes::CamerUBO>                  _CamerUBO
	);

	PipelineResourceConfig coloredQuadTransform_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::PrecomputedCamerUBO>    _PrecomputedCamerUBO,
		LinkedBindableBuffer<ShaderTypes::ObjectTransformBuffer>  _ObjectTransformBuffer,
		LinkedBindableBuffer<ShaderTypes::ObjectInstaceBuffer>    _ObjectInstaceBuffer
	);

	PipelineResourceConfig coloredTriangles_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::ColoredTriangleInstaceBuffer>  _ColoredTriangleInstaceBuffer,
		LinkedBindableBuffer<ShaderTypes::CamerUBO>                      _CamerUBO
	);

	PipelineResourceConfig lighting_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::mapFGObjectBuffer>         _mapFGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::baseLightingObjectBuffer>  _baseLightingObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapBGObjectBuffer>         _mapBGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::blurLightingObjectBuffer>  _blurLightingObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapUpscaleObjectBuffer>    _mapUpscaleObjectBuffer
	);

	PipelineResourceConfig lightingBlur_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::mapFGObjectBuffer>         _mapFGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::baseLightingObjectBuffer>  _baseLightingObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::blurLightingObjectBuffer>  _blurLightingObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapBGObjectBuffer>         _mapBGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapUpscaleObjectBuffer>    _mapUpscaleObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapBlurObjectBuffer>       _mapBlurObjectBuffer
	);

	PipelineResourceConfig lightingUpscale_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::mapFGObjectBuffer>         _mapFGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::baseLightingObjectBuffer>  _baseLightingObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::blurLightingObjectBuffer>  _blurLightingObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapBGObjectBuffer>         _mapBGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapUpscaleObjectBuffer>    _mapUpscaleObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapBlurObjectBuffer>       _mapBlurObjectBuffer
	);

	PipelineResourceConfig particleSystem_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::ParticalSmallGroupInstanceBuffer>  _ParticalSmallGroupInstanceBuffer,
		LinkedBindableBuffer<ShaderTypes::ParticalLargeGroupInstanceBuffer>  _ParticalLargeGroupInstanceBuffer,
		LinkedBindableBuffer<ShaderTypes::CamerUBO>                          _CamerUBO
	);

	PipelineResourceConfig particleSystemCompute_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::ParticalInstanceConfigBuffer>      _ParticalInstanceConfigBuffer,
		LinkedBindableBuffer<ShaderTypes::ParticalLargeGroupInstanceBuffer>  _ParticalLargeGroupInstanceBuffer,
		LinkedBindableBuffer<ShaderTypes::AtomicCounterBuffer>               _AtomicCounterBuffer
	);

	PipelineResourceConfig text_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::TextHeaderInstaceBuffer>  _TextHeaderInstaceBuffer,
		LinkedBindableBuffer<ShaderTypes::TextDataInstaceBuffer>    _TextDataInstaceBuffer,
		LinkedBindableBuffer<ShaderTypes::CamerUBO>                 _CamerUBO,
		LinkedBindableBuffer<ShaderTypes::TextIndexInstaceBuffer>   _TextIndexInstaceBuffer,
		GlobalImageDescriptor*                                      _texSampler
	);

	PipelineResourceConfig texture_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::TexturedQuadInstaceBuffer>  _TexturedQuadInstaceBuffer,
		LinkedBindableBuffer<ShaderTypes::LightMapUBO>                _LightMapUBO,
		LinkedBindableBuffer<ShaderTypes::CamerUBO>                   _CamerUBO,
		GlobalImageDescriptor*                                        _texSampler
	);

	PipelineResourceConfig tilemap_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::mapFGObjectBuffer>  _mapFGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapBGObjectBuffer>  _mapBGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::CamerUBO>           _CamerUBO,
		GlobalImageDescriptor*                                _texSampler
	);

	PipelineResourceConfig tilemapLightRaster_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::mapFGObjectBuffer>       _mapFGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapBGObjectBuffer>       _mapBGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapUpscaleObjectBuffer>  _mapUpscaleObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapBlurObjectBuffer>     _mapBlurObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::CamerUBO>                _CamerUBO,
		GlobalImageDescriptor*                                     _texSampler
	);


} // namespace
        