
#include "stdafx.h"

#include <stdint.h>

#include <VKEngine.h>
#include "pipeline.h"
#include "std140.h"
#include "ShaderTypes.h"

#include "ShaderUtility.h"

/*
    Generated by ShaderReflector tool
*/

namespace ShaderUtil
{
	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::ObjectTransformBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::ObjectTransformBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::transformObject) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::ObjectInstaceBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::ObjectInstaceBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::instanceDataObject) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::ColoredQuadInstaceBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::ColoredQuadInstaceBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::ColoredQuadInstance) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::ColoredTriangleInstaceBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::ColoredTriangleInstaceBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::ColoredTriangleInstance) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::mapFGObjectBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::mapFGObjectBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(int32_t) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::baseLightingObjectBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::baseLightingObjectBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::LightingUpdate) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::blurLightingObjectBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::blurLightingObjectBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::LightingUpdate) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::mapBGObjectBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::mapBGObjectBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(int32_t) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::mapUpscaleObjectBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::mapUpscaleObjectBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(int32_t) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::mapBlurObjectBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::mapBlurObjectBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(int32_t) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::ParticalInstanceConfigBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::ParticalInstanceConfigBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::ParticleSystemConfiguration) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::ParticalLargeGroupInstanceBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::ParticalLargeGroupInstanceBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::ParticleGroup_large) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::ParticalSmallGroupInstanceBuffer>(VKEngine* engine, MappedDoubleBuffer<ShaderTypes::ParticalSmallGroupInstanceBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::ParticleGroup_small) * 10, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::TexturedQuadInstaceBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::TexturedQuadInstaceBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::TexturedQuadInstance) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::TextHeaderInstaceBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::TextHeaderInstaceBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::TextHeader) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::TextDataInstaceBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::TextDataInstaceBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::CharQuad) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::TextIndexInstaceBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::TextIndexInstaceBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::LetterIndexInfo) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	PipelineResourceConfig coloredQuad_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::ColoredQuadInstaceBuffer>  _ColoredQuadInstaceBuffer,
		LinkedBindableBuffer<ShaderTypes::CamerUBO>                  _CamerUBO
	){
		PipelineResourceConfig con;
		con.bufferBindings = std::vector<BufferBinding> {
			BufferBinding(1, 0, _ColoredQuadInstaceBuffer),
			BufferBinding(0, 0, _CamerUBO),
		};
		return con;
	}

	PipelineResourceConfig coloredQuadTransform_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::PrecomputedCamerUBO>    _PrecomputedCamerUBO,
		LinkedBindableBuffer<ShaderTypes::ObjectTransformBuffer>  _ObjectTransformBuffer,
		LinkedBindableBuffer<ShaderTypes::ObjectInstaceBuffer>    _ObjectInstaceBuffer
	){
		PipelineResourceConfig con;
		con.bufferBindings = std::vector<BufferBinding> {
			BufferBinding(0, 0, _PrecomputedCamerUBO),
			BufferBinding(1, 0, _ObjectTransformBuffer),
			BufferBinding(0, 1, _ObjectInstaceBuffer),
		};
		return con;
	}

	PipelineResourceConfig coloredTriangles_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::ColoredTriangleInstaceBuffer>  _ColoredTriangleInstaceBuffer,
		LinkedBindableBuffer<ShaderTypes::CamerUBO>                      _CamerUBO
	){
		PipelineResourceConfig con;
		con.bufferBindings = std::vector<BufferBinding> {
			BufferBinding(0, 1, _ColoredTriangleInstaceBuffer),
			BufferBinding(0, 0, _CamerUBO),
		};
		return con;
	}

	PipelineResourceConfig lighting_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::mapFGObjectBuffer>         _mapFGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::baseLightingObjectBuffer>  _baseLightingObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapBGObjectBuffer>         _mapBGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::blurLightingObjectBuffer>  _blurLightingObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapUpscaleObjectBuffer>    _mapUpscaleObjectBuffer
	){
		PipelineResourceConfig con;
		con.bufferBindings = std::vector<BufferBinding> {
			BufferBinding(1, 0, _mapFGObjectBuffer),
			BufferBinding(0, 0, _baseLightingObjectBuffer),
			BufferBinding(1, 1, _mapBGObjectBuffer),
			BufferBinding(0, 1, _blurLightingObjectBuffer),
			BufferBinding(1, 2, _mapUpscaleObjectBuffer),
		};
		return con;
	}

	PipelineResourceConfig lightingBlur_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::mapFGObjectBuffer>         _mapFGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::baseLightingObjectBuffer>  _baseLightingObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::blurLightingObjectBuffer>  _blurLightingObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapBGObjectBuffer>         _mapBGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapUpscaleObjectBuffer>    _mapUpscaleObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapBlurObjectBuffer>       _mapBlurObjectBuffer
	){
		PipelineResourceConfig con;
		con.bufferBindings = std::vector<BufferBinding> {
			BufferBinding(1, 0, _mapFGObjectBuffer),
			BufferBinding(0, 0, _baseLightingObjectBuffer),
			BufferBinding(0, 1, _blurLightingObjectBuffer),
			BufferBinding(1, 1, _mapBGObjectBuffer),
			BufferBinding(1, 2, _mapUpscaleObjectBuffer),
			BufferBinding(1, 3, _mapBlurObjectBuffer),
		};
		return con;
	}

	PipelineResourceConfig lightingUpscale_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::mapFGObjectBuffer>         _mapFGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::baseLightingObjectBuffer>  _baseLightingObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::blurLightingObjectBuffer>  _blurLightingObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapBGObjectBuffer>         _mapBGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapUpscaleObjectBuffer>    _mapUpscaleObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapBlurObjectBuffer>       _mapBlurObjectBuffer
	){
		PipelineResourceConfig con;
		con.bufferBindings = std::vector<BufferBinding> {
			BufferBinding(1, 0, _mapFGObjectBuffer),
			BufferBinding(0, 0, _baseLightingObjectBuffer),
			BufferBinding(0, 1, _blurLightingObjectBuffer),
			BufferBinding(1, 1, _mapBGObjectBuffer),
			BufferBinding(1, 2, _mapUpscaleObjectBuffer),
			BufferBinding(1, 3, _mapBlurObjectBuffer),
		};
		return con;
	}

	PipelineResourceConfig particleSystem_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::ParticalSmallGroupInstanceBuffer>  _ParticalSmallGroupInstanceBuffer,
		LinkedBindableBuffer<ShaderTypes::ParticalLargeGroupInstanceBuffer>  _ParticalLargeGroupInstanceBuffer,
		LinkedBindableBuffer<ShaderTypes::CamerUBO>                          _CamerUBO
	){
		PipelineResourceConfig con;
		con.bufferBindings = std::vector<BufferBinding> {
			BufferBinding(0, 0, _ParticalSmallGroupInstanceBuffer),
			BufferBinding(0, 2, _ParticalLargeGroupInstanceBuffer),
			BufferBinding(0, 1, _CamerUBO),
		};
		return con;
	}

	PipelineResourceConfig particleSystemCompute_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::ParticalInstanceConfigBuffer>      _ParticalInstanceConfigBuffer,
		LinkedBindableBuffer<ShaderTypes::ParticalLargeGroupInstanceBuffer>  _ParticalLargeGroupInstanceBuffer,
		LinkedBindableBuffer<ShaderTypes::AtomicCounterBuffer>               _AtomicCounterBuffer
	){
		PipelineResourceConfig con;
		con.bufferBindings = std::vector<BufferBinding> {
			BufferBinding(0, 0, _ParticalInstanceConfigBuffer),
			BufferBinding(0, 1, _ParticalLargeGroupInstanceBuffer),
			BufferBinding(0, 2, _AtomicCounterBuffer),
		};
		return con;
	}

	PipelineResourceConfig text_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::TextHeaderInstaceBuffer>  _TextHeaderInstaceBuffer,
		LinkedBindableBuffer<ShaderTypes::TextDataInstaceBuffer>    _TextDataInstaceBuffer,
		LinkedBindableBuffer<ShaderTypes::CamerUBO>                 _CamerUBO,
		LinkedBindableBuffer<ShaderTypes::TextIndexInstaceBuffer>   _TextIndexInstaceBuffer,
		GlobalImageDescriptor*                                      _texSampler
	){
		PipelineResourceConfig con;
		con.bufferBindings = std::vector<BufferBinding> {
			BufferBinding(1, 1, _TextHeaderInstaceBuffer),
			BufferBinding(1, 2, _TextDataInstaceBuffer),
			BufferBinding(1, 0, _CamerUBO),
			BufferBinding(1, 3, _TextIndexInstaceBuffer),
		};
		con.globalDescriptors = std::vector<GlobalDescriptorBinding>{
			{0, _texSampler},
		};
		return con;
	}

	PipelineResourceConfig texture_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::TexturedQuadInstaceBuffer>  _TexturedQuadInstaceBuffer,
		LinkedBindableBuffer<ShaderTypes::LightMapUBO>                _LightMapUBO,
		LinkedBindableBuffer<ShaderTypes::CamerUBO>                   _CamerUBO,
		GlobalImageDescriptor*                                        _texSampler
	){
		PipelineResourceConfig con;
		con.bufferBindings = std::vector<BufferBinding> {
			BufferBinding(1, 0, _TexturedQuadInstaceBuffer),
			BufferBinding(1, 2, _LightMapUBO),
			BufferBinding(1, 1, _CamerUBO),
		};
		con.globalDescriptors = std::vector<GlobalDescriptorBinding>{
			{0, _texSampler},
		};
		return con;
	}

	PipelineResourceConfig tilemap_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::mapFGObjectBuffer>  _mapFGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapBGObjectBuffer>  _mapBGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::CamerUBO>           _CamerUBO,
		GlobalImageDescriptor*                                _texSampler
	){
		PipelineResourceConfig con;
		con.bufferBindings = std::vector<BufferBinding> {
			BufferBinding(1, 1, _mapFGObjectBuffer),
			BufferBinding(1, 2, _mapBGObjectBuffer),
			BufferBinding(1, 0, _CamerUBO),
		};
		con.globalDescriptors = std::vector<GlobalDescriptorBinding>{
			{0, _texSampler},
		};
		return con;
	}

	PipelineResourceConfig tilemapLightRaster_CreateBufferBindings(
		LinkedBindableBuffer<ShaderTypes::mapFGObjectBuffer>       _mapFGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapBGObjectBuffer>       _mapBGObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapUpscaleObjectBuffer>  _mapUpscaleObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::mapBlurObjectBuffer>     _mapBlurObjectBuffer,
		LinkedBindableBuffer<ShaderTypes::CamerUBO>                _CamerUBO,
		GlobalImageDescriptor*                                     _texSampler
	){
		PipelineResourceConfig con;
		con.bufferBindings = std::vector<BufferBinding> {
			BufferBinding(1, 1, _mapFGObjectBuffer),
			BufferBinding(1, 2, _mapBGObjectBuffer),
			BufferBinding(1, 3, _mapUpscaleObjectBuffer),
			BufferBinding(1, 4, _mapBlurObjectBuffer),
			BufferBinding(1, 0, _CamerUBO),
		};
		con.globalDescriptors = std::vector<GlobalDescriptorBinding>{
			{0, _texSampler},
		};
		return con;
	}


} // namespace
    