
#include "stdafx.h"

#include <stdint.h>

#include <VKEngine.h>

#include "std140.h"
#include "ShaderTypes.h"

#include "ShaderUtility.h"

/*
    Generated by ShaderReflector tool
*/

namespace ShaderUtil
{
	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::ObjectTransformBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::ObjectTransformBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::transformObject) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::ObjectInstaceBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::ObjectInstaceBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::instanceDataObject) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::ColoredQuadInstaceBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::ColoredQuadInstaceBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::ColoredQuadInstance) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::ColoredTriangleInstaceBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::ColoredTriangleInstaceBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::ColoredTriangleInstance) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::mapFGObjectBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::mapFGObjectBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(int32_t) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::baseLightingObjectBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::baseLightingObjectBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::LightingUpdate) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::blueLightingObjectBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::blueLightingObjectBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::LightingUpdate) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::mapBGObjectBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::mapBGObjectBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(int32_t) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::mapUpscaleObjectBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::mapUpscaleObjectBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(int32_t) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::mapBlurObjectBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::mapBlurObjectBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(int32_t) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::ParticalInstanceConfigBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::ParticalInstanceConfigBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::ParticleSystemConfiguration) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::ParticalLargeGroupInstanceBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::ParticalLargeGroupInstanceBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::ParticleGroup_large) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::ParticalSmallGroupInstanceBuffer>(VKEngine* engine, MappedDoubleBuffer<ShaderTypes::ParticalSmallGroupInstanceBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::ParticleGroup_small) * 10, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::TexturedQuadInstaceBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::TexturedQuadInstaceBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::TexturedQuadInstance) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::TextHeaderInstaceBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::TextHeaderInstaceBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::TextHeader) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::TextDataInstaceBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::TextDataInstaceBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::CharQuad) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}

	template<>
	void CreateMappedInstanceBuffer<ShaderTypes::TextIndexInstaceBuffer>(VKEngine* engine, uint32_t instanceCount, MappedDoubleBuffer<ShaderTypes::TextIndexInstaceBuffer>& buffer)
	{
		engine->createMappedBuffer(sizeof(ShaderTypes::LetterIndexInfo) * instanceCount, vk::BufferUsageFlagBits::eStorageBuffer, buffer);
	}


} // namespace
    