# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AssetPack

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AtlasLayout(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # AtlasLayout
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AtlasLayout
    def XCount(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # AtlasLayout
    def YCount(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateAtlasLayout(builder, xCount, yCount):
    builder.Prep(4, 8)
    builder.PrependInt32(yCount)
    builder.PrependInt32(xCount)
    return builder.Offset()
