# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AssetPack

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AtlasEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AtlasEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAtlasEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AtlasEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AtlasEntry
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AtlasEntry
    def UvMin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from AssetPack.vec2 import vec2
            obj = vec2()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AtlasEntry
    def UvMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from AssetPack.vec2 import vec2
            obj = vec2()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def AtlasEntryStart(builder):
    builder.StartObject(3)

def Start(builder):
    AtlasEntryStart(builder)

def AtlasEntryAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    AtlasEntryAddName(builder, name)

def AtlasEntryAddUvMin(builder, uvMin):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(uvMin), 0)

def AddUvMin(builder, uvMin):
    AtlasEntryAddUvMin(builder, uvMin)

def AtlasEntryAddUvMax(builder, uvMax):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(uvMax), 0)

def AddUvMax(builder, uvMax):
    AtlasEntryAddUvMax(builder, uvMax)

def AtlasEntryEnd(builder):
    return builder.EndObject()

def End(builder):
    return AtlasEntryEnd(builder)
