# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AssetPack

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Collider(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # Collider
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Collider
    def Type(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Collider
    def Radius(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # Collider
    def Scale(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 8)
        return obj


def CreateCollider(builder, type, radius, scale_x, scale_y):
    builder.Prep(4, 16)
    builder.Prep(4, 8)
    builder.PrependFloat32(scale_y)
    builder.PrependFloat32(scale_x)
    builder.PrependFloat32(radius)
    builder.PrependInt32(type)
    return builder.Offset()
