# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AssetPack

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Staticbody(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 20

    # Staticbody
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Staticbody
    def EntityId(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Staticbody
    def Collider(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 4)
        return obj


def CreateStaticbody(builder, entityId, collider_type, collider_radius, collider_scale_x, collider_scale_y):
    builder.Prep(4, 20)
    builder.Prep(4, 16)
    builder.Prep(4, 8)
    builder.PrependFloat32(collider_scale_y)
    builder.PrependFloat32(collider_scale_x)
    builder.PrependFloat32(collider_radius)
    builder.PrependInt32(collider_type)
    builder.PrependUint32(entityId)
    return builder.Offset()
