# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AssetPack

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class vec4(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # vec4
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # vec4
    def R(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # vec4
    def G(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # vec4
    def B(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # vec4
    def A(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))

def Createvec4(builder, r, g, b, a):
    builder.Prep(4, 16)
    builder.PrependFloat32(a)
    builder.PrependFloat32(b)
    builder.PrependFloat32(g)
    builder.PrependFloat32(r)
    return builder.Offset()
