#pragma once


// will need to create a loopup table similar to behaviours, but for instantiating tool subclasses keyed by item ID. 
// Should be an autogenerated header/extern source run before linking

class Tool {

	int holdSpriteAtlasIndex;

	virtual void OnClick() = 0;
	virtual void OnRelease() {};
};